### PR TITLE
Python 3.9 Big Sur bug fix

### PR DESCRIPTION
**Pull request by harripj**
App would run but not show window on MacOS Big Sur without this (temporary?) fix.

### CODE REVIEW

**Comment by din14970** [comment]
Apple with their silly OS updates. Thanks for the fix! Would you mind if I pull in some of your additions from your fork from time to time?

**Comment by din14970** [comment]
@harripj or if you want I can make you co-maintainer since you seem to be more actively working on this than me at this point

**Comment by harripj** [comment]
Yeah I've had a few problems with QT based programs, but this seems to be a catch all for now until PySide or Qt implement something better!

Yes absolutely no problem with pulling, it might be best if a second pair of eyes were to look it over before committing. Unfortunately VS Code auto-formatted my fork before I noticed to turn it off, so it may be laid out slightly differently!

**Comment by din14970** [comment]
yes I guess you are using black, I should use this too

**Comment by harripj** [comment]
> @harripj or if you want I can make you co-maintainer since you seem to be more actively working on this than me at this point

Happy to be! I'm just editing it to fit my needs but happy to contribute.

**Comment by harripj** [comment]
> yes I guess you are using black, I should use this too

Yes it's black.

**Comment by din14970** [comment]
> I'm just editing it to fit my needs

Probably the features you add may be useful to others is what I'm thinking

I sent you an invitation

**Pull request merged**
